blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/craftcms/commerce-stripe/discussions/new?category=ideas
    about: Start a new discussion about your idea
